name: "Battery Charge Dev"
description: "Charge Pv-Battery from grid"
version: "1.0.15"
slug: "pv_battery_charge_dev"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  gen24_ip_dns: 127.0.0.1
  forecast_latitude: 48.037222
  forecast_longitude: 14.416944
  forecast_declination: 24
  forecast_azimuth: -45
  forecast_modules_power: 14.35
  rule_charge: true
  rule_charge_start_hour: 23
  rule_charge_end_hour: 6
  rule_charge_hours_count: 3
  rule_charge_hours_power_1: 1000
  rule_charge_hours_power_2: 1000
  rule_charge_hours_power_3: 1000
  rule_charge_hours_power_4: 1000
  rule_charge_hours_power_5: 1000
schema:
  gen24_ip_dns: str
  forecast_latitude: float
  forecast_longitude: float
  forecast_declination: int
  forecast_azimuth: int
  forecast_modules_power: float
  rule_charge: bool
  rule_charge_start_hour: int(0,23)
  rule_charge_end_hour: int(0,23)
  rule_charge_hours_count: int(1,5)
  rule_charge_hours_power_1: int
  rule_charge_hours_power_2: int
  rule_charge_hours_power_3: int
  rule_charge_hours_power_4: int
  rule_charge_hours_power_5: int